// <auto-generated />
namespace BarberSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ClienteFornecedorContaspagarreceber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClienteFornecedorContaspagarreceber));
        
        string IMigrationMetadata.Id
        {
            get { return "201812062329540_Cliente-Fornecedor-Contas-pagar-receber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
